name = "Aged Pulsar"
author = "Timoti11"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "618e21d046333a43359153211f192a859cd6d9a56d97a8fa2ac6fe3f712790be"

[versions]
fabric = "0.15.5"
minecraft = "1.20.1"
