name = "Aged Pulsar"
author = "Timoti11"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40d4dc886ed0f054c9eb916c1bf182baff1cb7528a46fb419fd60ce8223225aa"

[versions]
fabric = "0.15.5"
minecraft = "1.20.1"
